from tkinter import *

# CRIANDO UMA JANELA
janela = Tk()

# ATRIBUINDO UM TÍTULO PARA MINHA JANELA
janela.title("Primeira GUI em Python")

# DEFININDO A COR DE FUNDO DA JANELA
janela['bg'] = '#000'

# DEFININDO O TAMANHO 500X250 POSICIONAMENTO DOS EIXOS X+Y
janela.geometry("800x600+200+200")

# TORNANDO UMA JANELA MAXIMIZAR DESATIVADO
janela.resizable(False, False)

# ALTERANDO O ÍCONE DA TELA
janela.iconbitmap("img/icon_001.ico")

# DEFININDO TAMANHO MÍNIMO E MÁXIMO DA JANELA
# janela.minsize(width=800,height=600) # PODEMOS SETAR O NOME DOS ATRIBUTOS QUE RECEBEM OS VALORES
# janela.maxsize(1000,800) # OU PODEMOS PASSAR OS VALORES DIRETAMENTE

# ABRINDO JANELA MAXIMIZADA ("zoomed") | MINIMIZADA ("iconic")
janela.state("zoomed") # QUANDO MINIMIZAMOS A TELA RETORNA PARA O VALOR DEFINIDOS EM GEOMETRY

# MANTÉM A JANELA ABERTA
janela.mainloop()